Temporary fix: Tag error cause crashes (why?) ``` Exception in thread Thread-16 (LaneChangeUpdater): Traceback (most recent call last):   File "threading.py", line 1075, in _bootstrap_inner   File "threading.py", line 1012, in run   File "E:\ETS2LA\origin\app\Plugins\HUD\main.py", line 614, in LaneChangeUpdater     status = status["Map"]              ~~~~~~^^^^^^^ TypeError: 'NoneType' object is not subscriptable Exception in thread Thread-11 (HudUpdater): Traceback (most recent call last):   File "threading.py", line 1075, in _bootstrap_inner   File "threading.py", line 1012, in run   File "E:\ETS2LA\origin\app\Plugins\HUD\main.py", line 450, in HudUpdater     distance = self.globals.tags.merge(distance)                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "E:\ETS2LA\origin\app\ETS2LA\Plugin\attributes.py", line 53, in merge     plugins = tag_dict.keys()               ^^^^^^^^^^^^^ AttributeError: 'bool' object has no attribute 'keys' ```