Force websockets v13.1
Version 14 and up implemented some changes that break some features. Relevant error:

`TypeError: server() missing 1 required positional argument: 'path'`